# Generated by Django 4.2.16 on 2024-09-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='noImage.png', null=True, upload_to=''),
        ),
    ]
